# Tested on Mac OS X 10.9 using clang compiler provided by XCode
package:
    name: opencv
    version: 3.0.0

source:
    fn: opencv-3.0.0.zip
    url: https://github.com/Itseez/opencv/archive/3.0.0.zip
build:
    number: 0

requirements:
    build:
        - cmake
        - numpy
        - jpeg
        - zlib
        - libpng
        - python
        - ffmpeg
        - x264
        - openssl
    run:
        - python
        - numpy
        - jpeg
        - zlib
        - libpng
        - ffmpeg
        - x264
        - openssl
test:
    imports:
      - cv2
      - cv2.cv

about:
    home: http://opencv.org/
    license: BSD
