package:
  name: cmake
  version: 3.3.0

source:
  fn: cmake-3.3.0.tar.gz
  url: http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz
  md5: b1d4823e3f74c961486d9f253da9825d 
test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
